project:
  type: website
  output-dir: docs

website:
  title: "Personal Page of Mojtaba Masoudinejad"
  description: "Mojtaba Masoudinejad is a senior machine learning engineer at the Bosch center for Artificial Intelligence (BCAI)"
  site-url: "https://www.masoudinejad.xyz"
  repo-url: "https://github.com/masoudinejad/masoudinejad.github.io"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: publications.qmd
        text: Publications
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:masoudinejad@gmail.com"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/masoudinejad
        rel: me
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/mojtaba-masoudinejad/
        rel: me
  page-footer:
    center: |
      <span class="faux-block"> Mojtaba Masoudinejad -- 2024</span>

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full
editor: visual

