project:
  type: website
  output-dir: docs

website:
  title: "Personal Page of Mojtaba Masoudinejad"
  description: "Mojtaba Masoudinejad is a senior machine learning engineer at the Bosch center for Artificial Intelligence (BCAI)"
  site-url: "https://www.masoudinejad.xyz"
  repo-url: "https://github.com/masoudinejad/masoudinejad.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full
editor: visual

