---
title: "Publications"
---
* M. Yayla et al. “[TREAM: A Tool for Evaluating Error Resilience of Tree-Based Models Using Approximate Memory](https://link.springer.com/chapter/10.1007/978-3-031-15074-6_4)”. In: Embedded Computer Systems: Architectures, Modeling, and Simulation. Ed. by Alex Orailoglu, Marc Reichenbach, and Matthias Jung. Lecture Notes in Computer Science. Cham: Springer International Publishing, 2022, pp. 61–73. ISBN: 978-3-031-15074-6. DOI: 10.1007/978-3-031-15074-6_4

* M. Masoudinejad; "[Modeling energy supply unit of ultra-low power devices with indoor photovoltaic harvesting](http://dx.doi.org/10.17877/DE290R-21657)" PhD Dissertation in Eldorado - Repository of the TU Dortmund University; Dortmund, Germany; 2020.
* M. Masoudinejad; "[Open-Loop Dynamic Modeling of Low-Budget Batteries with Low-Power Loads](https://doi.org/10.3390/batteries6040050)" in journal of Batteries, vol. 6, no. 4, p. 50; Publisher: Multidisciplinary Digital Publishing Institute (MDPI); 2020.
* M. Masoudinejad; “[Data-sets for indoor photovoltaic behavior in low lighting conditions](https://doi.org/10.3390/data5020032)” in journal of Data, vol. 5, no. 2, p. 32, Number: 2; Publisher: Multidisciplinary Digital Publishing Institute (MDPI); 2020.
* M. Masoudinejad; "[Data-sets for Indoor Photovoltaic Behavior in Low Lighting condition](https://doi.org/10.5281/zenodo.3697105)" dataset in Zenodo; 2020.
* M. ten Hompel et al; “[Automatic Identification Technology](https://doi.org/10.1007/978-3-319-92447-2_30)” Book chapter in: Operations, Logistics and Supply Chain Management. Lecture Notes in Logistics, pp. 687–718; Springer International Publishing, Cham; ISBN: 978-3-319-92447-2; 2019.
* M. Masoudinejad et al; “[Average Modelling of State-of-the-Art Ultra-low Power Energy Harvesting Converter IC](https://doi.org/10.1109/SPEEDAM.2018.8445303)” in proceedings of 2018 International Symposium on Power Electronics, Electrical Drives, Automation and Motion, pp. 99–104; Amalfi, Italy; 2018.
* M. Masoudinejad; "[Large Signal Converter Data from Texas Instruments BQ25570](https://doi.org/10.17877/fd72wij6yo)" dataset in SFB876 TU Dortmund University; Dortmund, Germany; 2018.
* M. Masoudinejad; "[Large Signal Converter Data from Texas Instruments BQ25505](https://doi.org/10.17877/fd72o6mn0g)" dataset in SFB876 TU Dortmund University; Dortmund, Germany; 2018.
* M. Masoudinejad; "[Models and training datasets for Texas Instruments BQ25505 and BQ25570 ICs](https://doi.org/10.17877/FE0O0YSXS0)" dataset in SFB876, TU Dortmund University; Dortmund, Germany; 2018.
* M. Masoudinejad; "[Power analysis of PhyNode](files/TechReport2018.pdf)" in 2018 Annual Technical Reports of SFB876; TU Dortmund University; Dortmund, Germany; 2018.
* M. Masoudinejad et al. “[Machine Learning Based Indoor Localisation Using Environmental Data in PhyNetLab Warehouse](https://ieeexplore.ieee.org/abstract/document/8435922)” in proceedings of European Conference on Smart Objects, Systems and Technologies (Smart SysTech), pp. 1–8; 2018.
* M. Masoudinejad; "[Data Collection for Modelling Power Chargers in Energy Harvesting](files/TechReport2017.pdf)" in 2017 Annual Technical Reports of SFB876; TU Dortmund University; Dortmund, Germany; 2017.
* R. Falkenberg et al.; “[PhyNetLab: An IoT-based warehouse testbed](https://annals-csis.org/proceedings/2017/drp/pdf/267.pdf)” in proceedings of Federated Conference on Computer Science and Information Systems (FedCSIS), pp. 1051–1055; 2017.
* M. Masoudinejad; "[Automated Data Collection for Modelling Texas Instruments Ultra Low-Power Chargers](https://sfb876.tu-dortmund.de/PublicPublicationFiles/masoudinejad_2017b.pdf)" Technical Report in SFB876; TU Dortmund University; Dortmund, Germany; 2017. 
* M. Masoudinejad; "[A Power Model for DC-DC Boost Converters Operating in PFM Mode](https://sfb876.tu-dortmund.de/PublicPublicationFiles/masoudinejad_2017a.pdf)" Technical Report in SFB876;  TU Dortmund University; Dortmund, Germany; 2017.
* M. Masoudinejad et al.; “[Smart Sensing Devices for Logistics Application](https://doi.org/10.1007/978-3-319-61563-9_4)” in Sensor Systems and Software. Vol. 205. Springer International Publishing, pp. 41–52. ISBN: 978-3-319-61562-2 978-3-319-61563-9; 2017
* M. Masoudinejad; "[Photovoltaic Energy Harvesting Characteristics under Ultra-Low Light](https://sfb876.tu-dortmund.de/PublicPublicationFiles/sfbgk_etal_2016a.pdf)" in 2016 Annual Technical Reports of SFB876, pp.41-44; TU Dortmund University, Dortmund, Germany; 2016.
* S. Feldhorst et al.; “[Motion classification for analyzing the order picking process using mobile sensors](https://doi.org/10.5220/0005828407060713)” in proceedings of the 5th international conference on pattern recognition applications and methods. SCITEPRESS-Science and Technology Publications, Lda, pp. 706–713. ISBN: 978-989-758-173-1; 2016.
* M. Masoudinejad et al.; “[A gray box modeling of a photovoltaic cell under low illumination in materials handling application](https://doi.org/10.1109/IRSEC.2015.7455081)” in proceedings of IEEE 3rd International Renewable and Sustainable Energy Conference (IRSEC), pp. 1–6; 2015.
* M. Masoudinejad; "[A Measurement Platform for Photovoltaic Energy Harvesting in Indoor Low Light Environment](files/TechReport2015.pdf)" in 2015 Annual Technical Reports of SFB876; TU Dortmund University, Dortmund, Germany; 2015.
* M. Masoudinejad et al.; “[A measurement platform for photovoltaic performance analysis in environments with ultra-low energy harvesting potential](https://doi.org/10.1016/j.scs.2015.09.006)” in journal of Sustainable Cities and Society 25, pp. 74–81. ISSN: 22106707; 2015.
* M. Masoudinejad et al.; “[Development of a measurement platform for indoor photovoltaic energy harvesting in materials handling applications](https://doi.org/10.1109/IREC.2015.7110938)” in proceedings of 6th International Renewable Energy Congress (IREC), pp. 1–6. ISBN: 978-1-4799-7947-9; 2015.
* M. Masoudinejad et al.; “[Reduction of Energy Consumption by Proper Speed Selection in PMSM-Driven Roller Conveyors](https://doi.org/10.1109/TIA.2014.2360013)” in IEEE Transactions on Industry Applications 51.2, pp. 1572–1578. ISSN: 00939994; 2015.
* M. Roidl et al.; “[Performance Availability Evaluation of Smart Devices in Materials Handling Systems](https://doi.org/10.1109/ICCChinaW.2014.7107857)” in proceedings of  IEEE ICCC Workshops on Internet of Things, pp. 6–10. ISBN: 978-1-4799-6707-0; 2014.
* M. Roidl et al.; “[Entwicklung eines Versuchsfelds für grosse Systeme intelligenter Behälter](https://doi.org/10.2195/lj_Proc_roidl_de_201411_01)” in Logistics Journal 2014; ISSN: 18607977; 2014.
* M. Masoudinejad et al.; “[Energy optimized speed regulation of permanent magnet synchronous motors for driving roller conveyors](https://doi.org/10.1109/PEDS.2013.6527070)” in proceedings of the International Conference on Power Electronics and Drive Systems, pp. 500–505. ISBN: 978-1-4673-1790-0; 2013.
* M. Masoudinejad; “Optimization of Shuttle Robots Management in a SABIC High Rise Warehouse” Master’s thesis; TU Dortmund University, Dortmund, Germany; 2011
* M. Masoudinejad et al.; “[Real-time level plant control using improved BELBIC](https://doi.org/10.3182/20080706-5-KR-1001.00779)” in proceedings of 17th IFAC World Congress. Vol. 17. Seoul, Korea, 2008. ISBN: 978-3-902661-00-5; 2008.
* M. Masoudinejad and R. Khorsandi; “[Design and implementation of Brain Emotional Learning Based Intelligent Controller (BELBIC) for a level pilot plant](files/BELBIC_thesis.pdf)” Bachelor’s thesis; Khaje Nasir Toosi University of Technology; Tehran, Iran; 2007.
* M. Masoudinejad; “[Iran Khodro Stock Market Estimation Using Polynomial Neural Networks](https://civilica.com/doc/48670/)” in proceedings of 9th Iranian Student Conference on Electrical Engineering; Tehran, Iran; 2006.
* M. Masoudinejad; “[Analysis of the Karkhe Dam Automatic Voltage Regulator](https://civilica.com/doc/47220/)” in proceedings of 8th Iranian Student Conference on Electrical Engineering; Kerman, Iran; 2005.